server:
  port: 8083
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      # routes:
      #   - id: registry-service
      #     uri: http://localhost:
      #     predicates:
      #       -Path=/registry/**