server:
  port: 8011
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
spring:
  config:
      import: 'optional:configserver:'
  datasource:
    one:
      driver-class-name: org.MongoDriver.Driver
      url: jdbc:mongo://localhost:27017/db_products
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: db_products