server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
spring:
  data:
    mongodb:
      database: db_products
      port: 27017
      host: localhost
      username: root
logging:
  config:
    classpath: logback-test.xml
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      client:
        base-config: default
  #timeout
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      client:
         base-config: default