server:
  port: 8010
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
spring:
  data:
    mongodb:
      database: db_products
      port: 27017
      host: localhost
      username: root
logging:
  config:
    classpath: logback-test.xml