server:
  port: 8006
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8009/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  config:
      import: 'optional:configserver:'
  datasource:
    one:
      driver-class-name: org.MongoDriver.Driver
      url: jdbc:mongo://localhost:27017/db_products
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: db_products

logging:
  config:
    classpath: logback-test.xml
resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
    instances:
      movement:
        base-config: default
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
    instances:
      movement:
        base-config: default