server:
  port: 8006
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  config:
      import: 'optional:configserver:'
  datasource:
    one:
      driver-class-name: org.MongoDriver.Driver
      url: jdbc:mongo://localhost:27017/db_products
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: db_products

logging:
  config:
    classpath: logback.xml