server:
  port: 8005
management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: db_products

logging:
  config:
    classpath: logback-test.xml